import "./Assign New Cases/assign-new-cases-background.js"
import "./Cases Navigation/cases-navigation-background.js"
import "./Close Case/close-case-background.js"
import "./Context Actions/context-actions-background.js"
import "./Detect Last Alert/detect-last-alert-background.js"
import "./Entity Enrichment/entity-enrichment-background.js"
import "./Hide Recommendations/hide-recommendations-background.js"
import "./Insert CSS/insert-css-background.js"
import "./Quick Copy/quick-copy-background.js"